### ISSUE TITLE
certificates should NOT be validated clientside

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-client-go#24]
https://github.com/taskcluster/taskcluster-client-go/blob/ef986255fc07c3e92184384d7b6cdc528008ecba/creds.go#L210

Client side validate should be held to a minimum... IMO certificate should NOT be read client side... Why would you want this?

This means that `taskcluster-client-go` breaks whenever we update the certificate format. If we introduce a certificate version 2, why shouldn't the client library be able to use it?

Note: I think it's reasonable to have a `certificate.IsExpired()` helper function, that people can **choose** to call, but it should **not** be called whenever you create a client. As that would break _forward compatibility_.

**Comment by petemoore** [comment]
Fixed in #30.
