### ISSUE TITLE
credentials should NOT be validated

### ISSUE THREAD

**Issue by jonasfj** [taskcluster/taskcluster-client-go#25]
https://github.com/taskcluster/taskcluster-client-go/blob/ef986255fc07c3e92184384d7b6cdc528008ecba/creds.go#L210

These regular expressions should not be enforced client side...

This makes it super hard to mock things... and it enforces restrictions we have serverside on the client side... this is completely unnecessary.

If you supply invalid credentials you get a 401 when you try to use them... We use dummy credentials locally all the time. This breaks usage patterns we have in taskcluster-worker for integration testing against a mock queue.

----
generally speaking things like this only serve to complicate our lives. It causes tight coupling and when using the client library like this we have to check for errors in places where they make no sense...
ie. if I was to get an error because of bad credentials I might as well get it when I make a request, getting it earlier just serves to complicate my code with unnecessary error handling.

Regardless of how well the initial validation is here, nothing can prevent an authentication or authorization error from happening when I make a request, so if we're going to return an error because of bad credentials it might as well be from the server. That way I have one less kind of error to deal with.

**Comment by jonasfj** [comment]
@petemoore I had a quick look at this, but the code is a bit hard to read... maybe we could use multi-line strings? in the code templates :)

**Comment by petemoore** [comment]
Fixed in #30.
